import { Grid } from "./Grid";
import { Level } from "./Level";
import type { Position } from "./types";

const path = (points: Position[]) => points;

export const levels = [
  new Level({
    id: 1,
    title: "The Thirsty Crow",
    story:
      "Guide the crow to collect stones, drop them into the pot, and raise the water.",
    concept: "Repeating an action with a loop",
    grid: new Grid(
      5,
      5,
      path([
        { x: 0, y: 2 },
        { x: 1, y: 2 },
        { x: 2, y: 2 },
        { x: 3, y: 2 },
        { x: 4, y: 2 },
      ]),
    ),
    start: { x: 0, y: 2 },
    direction: "east",
    characterSprite: "crow",
    goal: {
      type: "dropStones",
      position: { x: 4, y: 2 },
      required: 3,
      label: "Raise the water",
    },
    obstacles: [
      { id: "tree-crow-a", kind: "tree", position: { x: 1, y: 0 }, sprite: "tree" },
      { id: "tree-crow-b", kind: "tree", position: { x: 3, y: 4 }, sprite: "tree" },
    ],
    objects: [
      { id: "stone-1", kind: "stone", position: { x: 1, y: 2 }, sprite: "stone" },
      { id: "stone-2", kind: "stone", position: { x: 2, y: 2 }, sprite: "stone" },
      { id: "stone-3", kind: "stone", position: { x: 3, y: 2 }, sprite: "stone" },
      { id: "pot", kind: "pot", position: { x: 4, y: 2 }, sprite: "pot" },
    ],
    theme: "crow",
    successText: "The water rises high enough for the crow to drink.",
    starterProgram: [
      "move_forward",
      "pick_object",
      "move_forward",
      "pick_object",
      "move_forward",
      "pick_object",
      "move_forward",
      "repeat_loop:3:drop_object",
    ],
  }),
  new Level({
    id: 2,
    title: "Monkey Mango Maze",
    story:
      "A hungry monkey wants every mango. Plan a longer route around the trees and collect them in order.",
    concept: "Longer sequencing with loops and collection steps",
    grid: new Grid(
      7,
      6,
      path([
        { x: 0, y: 5 },
        { x: 1, y: 5 },
        { x: 2, y: 5 },
        { x: 2, y: 4 },
        { x: 2, y: 3 },
        { x: 3, y: 3 },
        { x: 4, y: 3 },
        { x: 4, y: 2 },
        { x: 4, y: 1 },
        { x: 5, y: 1 },
        { x: 6, y: 1 },
        { x: 6, y: 2 },
        { x: 6, y: 3 },
        { x: 6, y: 4 },
        { x: 5, y: 4 },
        { x: 4, y: 4 },
        { x: 3, y: 4 },
        { x: 2, y: 4 },
        { x: 1, y: 4 },
        { x: 1, y: 3 },
        { x: 1, y: 2 },
      ]),
    ),
    start: { x: 0, y: 5 },
    direction: "east",
    characterSprite: "monkey",
    goal: { type: "collectAll", itemKind: "mango", label: "Collect all mangoes" },
    obstacles: [
      { id: "tree-m-a", kind: "tree", position: { x: 0, y: 2 }, sprite: "tree" },
      { id: "tree-m-b", kind: "tree", position: { x: 1, y: 1 }, sprite: "tree" },
      { id: "tree-m-c", kind: "tree", position: { x: 2, y: 2 }, sprite: "tree" },
      { id: "tree-m-d", kind: "tree", position: { x: 3, y: 2 }, sprite: "tree" },
      { id: "tree-m-e", kind: "tree", position: { x: 3, y: 5 }, sprite: "tree" },
      { id: "tree-m-f", kind: "tree", position: { x: 5, y: 2 }, sprite: "tree" },
      { id: "tree-m-g", kind: "tree", position: { x: 5, y: 3 }, sprite: "tree" },
      { id: "tree-m-h", kind: "tree", position: { x: 5, y: 5 }, sprite: "tree" },
    ],
    objects: [
      {
        id: "mango-tree",
        kind: "decoration",
        position: { x: 4, y: 0 },
        sprite: "mangoTree",
      },
      { id: "mango-1", kind: "mango", position: { x: 2, y: 5 }, sprite: "mango" },
      { id: "mango-2", kind: "mango", position: { x: 4, y: 3 }, sprite: "mango" },
      { id: "mango-3", kind: "mango", position: { x: 6, y: 1 }, sprite: "mango" },
      { id: "mango-4", kind: "mango", position: { x: 1, y: 2 }, sprite: "mango" },
    ],
    theme: "monkey",
    successText: "The monkey has every mango in the basket.",
    starterProgram: [
      "repeat_loop:2:move_forward",
      "pick_object",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
      "pick_object",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
      "pick_object",
      "turn_right",
      "repeat_loop:3:move_forward",
      "turn_right",
      "repeat_loop:5:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
      "pick_object",
    ],
  }),
  new Level({
    id: 3,
    title: "Little Red's Forked Forest",
    story:
      "Help Little Red Riding Hood choose the safe trail to Grandma's house. Some forked paths look shorter, but wolves are waiting there.",
    concept: "Choosing a path while avoiding hazards",
    grid: new Grid(
      7,
      6,
      path([
        { x: 0, y: 5 },
        { x: 1, y: 5 },
        { x: 2, y: 5 },
        { x: 3, y: 5 },
        { x: 4, y: 5 },
        { x: 4, y: 4 },
        { x: 4, y: 3 },
        { x: 5, y: 3 },
        { x: 6, y: 3 },
        { x: 6, y: 2 },
        { x: 6, y: 1 },
        { x: 6, y: 0 },
        { x: 2, y: 4 },
        { x: 2, y: 3 },
        { x: 3, y: 3 },
        { x: 5, y: 2 },
        { x: 5, y: 1 },
        { x: 5, y: 5 },
        { x: 6, y: 5 },
        { x: 6, y: 4 },
      ]),
    ),
    start: { x: 0, y: 5 },
    direction: "east",
    characterSprite: "littleRed",
    goal: { type: "reach", position: { x: 6, y: 0 }, label: "Grandma's house" },
    obstacles: [
      { id: "wolf-shortcut", kind: "wolf", position: { x: 3, y: 3 }, sprite: "wolf" },
      { id: "wolf-north", kind: "wolf", position: { x: 5, y: 2 }, sprite: "wolf" },
      { id: "wolf-bottom", kind: "wolf", position: { x: 6, y: 4 }, sprite: "wolf" },
      { id: "tree-r-a", kind: "tree", position: { x: 0, y: 2 }, sprite: "tree" },
      { id: "tree-r-b", kind: "tree", position: { x: 1, y: 1 }, sprite: "tree" },
      { id: "tree-r-c", kind: "tree", position: { x: 3, y: 1 }, sprite: "tree" },
      { id: "tree-r-d", kind: "tree", position: { x: 4, y: 2 }, sprite: "tree" },
      { id: "tree-r-e", kind: "tree", position: { x: 1, y: 4 }, sprite: "tree" },
    ],
    objects: [
      {
        id: "grandma-house",
        kind: "house",
        position: { x: 6, y: 0 },
        sprite: "grandmaHouse",
      },
    ],
    theme: "red",
    successText: "Grandma opens the door. Safe path chosen!",
    starterProgram: [
      "repeat_loop:4:move_forward",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
      "turn_left",
      "repeat_loop:3:move_forward",
    ],
  }),
  new Level({
    id: 4,
    title: "The Clever Rabbit",
    story:
      "A proud lion scares every animal in the forest. A tiny rabbit has a clever idea: lead the lion to an old well, where the lion will think his own reflection is another lion. Guide the rabbit safely to the well and avoid the lion's trap paths.",
    concept: "Debugging a route with turns and safe choices",
    grid: new Grid(
      6,
      6,
      path([
        { x: 0, y: 5 },
        { x: 1, y: 5 },
        { x: 2, y: 5 },
        { x: 2, y: 4 },
        { x: 2, y: 3 },
        { x: 3, y: 3 },
        { x: 4, y: 3 },
        { x: 4, y: 2 },
        { x: 4, y: 1 },
        { x: 5, y: 1 },
        { x: 5, y: 0 },
        { x: 1, y: 4 },
        { x: 2, y: 2 },
        { x: 3, y: 2 },
        { x: 5, y: 3 },
        { x: 5, y: 2 },
      ]),
    ),
    start: { x: 0, y: 5 },
    direction: "east",
    characterSprite: "rabbit",
    goal: { type: "reach", position: { x: 5, y: 0 }, label: "Old well" },
    obstacles: [
      { id: "lion-shortcut", kind: "lion", position: { x: 2, y: 2 }, sprite: "lion" },
      { id: "lion-bend", kind: "lion", position: { x: 5, y: 3 }, sprite: "lion" },
      { id: "tree-p-a", kind: "tree", position: { x: 0, y: 2 }, sprite: "tree" },
      { id: "tree-p-b", kind: "tree", position: { x: 1, y: 1 }, sprite: "tree" },
      { id: "tree-p-c", kind: "tree", position: { x: 3, y: 5 }, sprite: "tree" },
      { id: "tree-p-d", kind: "tree", position: { x: 5, y: 5 }, sprite: "tree" },
    ],
    objects: [
      { id: "old-well", kind: "decoration", position: { x: 5, y: 0 }, sprite: "well" },
    ],
    theme: "panchatantra",
    successText: "The rabbit reaches the well and outsmarts the lion.",
    starterProgram: [
      "repeat_loop:2:move_forward",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "move_forward",
      "turn_left",
      "move_forward",
    ],
  }),
  new Level({
    id: 5,
    title: "Monkey and Crocodile",
    story:
      "A monkey lives in a mango tree by the river. A crocodile pretends to be friendly, but the monkey must think fast and return safely to the tree. Plan a route around the crocodiles and do not trust the tempting shortcuts.",
    concept: "Planning a safe path around hazards",
    grid: new Grid(
      7,
      6,
      path([
        { x: 0, y: 4 },
        { x: 1, y: 4 },
        { x: 2, y: 4 },
        { x: 2, y: 3 },
        { x: 2, y: 2 },
        { x: 3, y: 2 },
        { x: 4, y: 2 },
        { x: 4, y: 1 },
        { x: 4, y: 0 },
        { x: 5, y: 0 },
        { x: 6, y: 0 },
        { x: 3, y: 4 },
        { x: 4, y: 4 },
        { x: 5, y: 4 },
        { x: 5, y: 3 },
        { x: 5, y: 2 },
        { x: 6, y: 2 },
      ]),
    ),
    start: { x: 0, y: 4 },
    direction: "east",
    characterSprite: "monkey",
    goal: { type: "reach", position: { x: 6, y: 0 }, label: "Mango tree" },
    obstacles: [
      { id: "croc-shortcut", kind: "crocodile", position: { x: 5, y: 2 }, sprite: "crocodile" },
      { id: "croc-river", kind: "crocodile", position: { x: 3, y: 4 }, sprite: "crocodile" },
      { id: "tree-croc-a", kind: "tree", position: { x: 0, y: 1 }, sprite: "tree" },
      { id: "tree-croc-b", kind: "tree", position: { x: 1, y: 2 }, sprite: "tree" },
      { id: "tree-croc-c", kind: "tree", position: { x: 3, y: 0 }, sprite: "tree" },
      { id: "tree-croc-d", kind: "tree", position: { x: 6, y: 5 }, sprite: "tree" },
    ],
    objects: [
      { id: "safe-mango-tree", kind: "decoration", position: { x: 6, y: 0 }, sprite: "mangoTree" },
      { id: "river-mango", kind: "mango", position: { x: 4, y: 2 }, sprite: "mango" },
    ],
    theme: "panchatantra",
    successText: "The monkey reaches the tree and keeps clear of the crocodiles.",
    starterProgram: [
      "repeat_loop:2:move_forward",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
      "turn_left",
      "repeat_loop:2:move_forward",
      "turn_right",
      "repeat_loop:2:move_forward",
    ],
  }),
];
